export const createWorkergroupParams = [
	{ name: 'Endpoint Name', value: 'endpoint_name' },
	{ name: 'Endpoint ID', value: 'endpoint_id' },
	{ name: 'Template Hash', value: 'template_hash' },
	{ name: 'Template ID', value: 'template_id' },
	{ name: 'Search Params', value: 'search_params' },
	{ name: 'Launch Args', value: 'launch_args' },
	{ name: 'Min Load', value: 'min_load' },
	{ name: 'Target Util', value: 'target_util' },
	{ name: 'Cold Mult', value: 'cold_mult' },
	{ name: 'Cold Workers', value: 'cold_workers' },
	{ name: 'Max Workers', value: 'max_workers' },
	{ name: 'Test Workers', value: 'test_workers' },
	{ name: 'GPU RAM', value: 'gpu_ram' },
];
