// search_offers.ts
export const searchOffersParams = [
  { name: 'Allocated Storage', value: 'allocated_storage' },
  { name: 'BW Nvlink', value: 'bw_nvlink' },
  { name: 'Compute Cap', value: 'compute_cap' },
  { name: 'CPU Arch', value: 'cpu_arch' },
  { name: 'CPU Cores', value: 'cpu_cores' },
  { name: 'CPU GHz', value: 'cpu_ghz' },
  { name: 'CUDA Max Good', value: 'cuda_max_good' },
  { name: 'Datacenter', value: 'datacenter' },
  { name: 'Direct Port Count', value: 'direct_port_count' },
  { name: 'Disable Bundling', value: 'disable_bundling' },
  { name: 'Disk BW', value: 'disk_bw' },
  { name: 'DLPerf', value: 'dlperf' },
  { name: 'DLPerf Per Dphtotal', value: 'dlperf_per_dphtotal' },
  { name: 'DLPerf USD', value: 'dlperf_usd' },
  { name: 'Driver Version', value: 'driver_version' },
  { name: 'Duration', value: 'duration' },
  { name: 'External', value: 'external' },
  { name: 'Flops USD', value: 'flops_usd' },
  { name: 'Geolocation', value: 'geolocation' },
  { name: 'GPU Arch', value: 'gpu_arch' },
  { name: 'GPU Display Active', value: 'gpu_display_active' },
  { name: 'GPU Frac', value: 'gpu_frac' },
  { name: 'GPU Max Power', value: 'gpu_max_power' },
  { name: 'GPU Max Temp', value: 'gpu_max_temp' },
  { name: 'GPU Mem BW', value: 'gpu_mem_bw' },
  { name: 'GPU Name', value: 'gpu_name' },
  { name: 'GPU RAM', value: 'gpu_ram' },
  { name: 'GPU Total RAM', value: 'gpu_total_ram' },
  { name: 'Has AVX', value: 'has_avx' },
  { name: 'Inet Down', value: 'inet_down' },
  { name: 'Inet Up', value: 'inet_up' },
  { name: 'Limit', value: 'limit' },
  { name: 'Machine ID', value: 'machine_id' },
  { name: 'Num GPUs', value: 'num_gpus' },
  { name: 'Order', value: 'order' },
  { name: 'PCI Gen', value: 'pci_gen' },
  { name: 'Reliability2', value: 'reliability2' },
  { name: 'Rentable', value: 'rentable' },
  { name: 'Rented', value: 'rented' },
  { name: 'Static IP', value: 'static_ip' },
  { name: 'Storage Cost', value: 'storage_cost' },
  { name: 'Total Flops', value: 'total_flops' },
  { name: 'Type', value: 'type' },
  { name: 'Ubuntu Version', value: 'ubuntu_version' },
  { name: 'Verified', value: 'verified' },
  { name: 'VMs Enabled', value: 'vms_enabled' },
];
